package com.ogesture.ui.theme

import androidx.compose.ui.graphics.Color

// Material 3 tonal palette seeded from a deep blue (#0061A4).
// Used on Android < 12 and whenever dynamic color is unavailable.

// Light scheme
val LightPrimary = Color(0xFF0061A4)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD1E4FF)
val LightOnPrimaryContainer = Color(0xFF001D36)
val LightSecondary = Color(0xFF535F70)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD7E3F7)
val LightOnSecondaryContainer = Color(0xFF101C2B)
val LightTertiary = Color(0xFF6B5778)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFF2DAFF)
val LightOnTertiaryContainer = Color(0xFF251431)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF8F9FD)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFF8F9FD)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFDFE2EB)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightOutline = Color(0xFF73777F)
val LightOutlineVariant = Color(0xFFC3C7CF)
val LightInverseSurface = Color(0xFF2F3033)
val LightInverseOnSurface = Color(0xFFF1F0F4)
val LightInversePrimary = Color(0xFF9ECAFF)
val LightSurfaceDim = Color(0xFFD9DAE0)
val LightSurfaceBright = Color(0xFFF8F9FD)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF2F3F9)
val LightSurfaceContainer = Color(0xFFECEEF4)
val LightSurfaceContainerHigh = Color(0xFFE7E8EE)
val LightSurfaceContainerHighest = Color(0xFFE1E2E8)

// Dark scheme
val DarkPrimary = Color(0xFF9ECAFF)
val DarkOnPrimary = Color(0xFF003258)
val DarkPrimaryContainer = Color(0xFF00497D)
val DarkOnPrimaryContainer = Color(0xFFD1E4FF)
val DarkSecondary = Color(0xFFBBC7DB)
val DarkOnSecondary = Color(0xFF253140)
val DarkSecondaryContainer = Color(0xFF3B4858)
val DarkOnSecondaryContainer = Color(0xFFD7E3F7)
val DarkTertiary = Color(0xFFD6BEE4)
val DarkOnTertiary = Color(0xFF3B2948)
val DarkTertiaryContainer = Color(0xFF523F5F)
val DarkOnTertiaryContainer = Color(0xFFF2DAFF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF111318)
val DarkOnBackground = Color(0xFFE2E2E6)
val DarkSurface = Color(0xFF111318)
val DarkOnSurface = Color(0xFFE2E2E6)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC3C7CF)
val DarkOutline = Color(0xFF8D9199)
val DarkOutlineVariant = Color(0xFF43474E)
val DarkInverseSurface = Color(0xFFE2E2E6)
val DarkInverseOnSurface = Color(0xFF2F3033)
val DarkInversePrimary = Color(0xFF0061A4)
val DarkSurfaceDim = Color(0xFF111318)
val DarkSurfaceBright = Color(0xFF37393E)
val DarkSurfaceContainerLowest = Color(0xFF0C0E13)
val DarkSurfaceContainerLow = Color(0xFF191C20)
val DarkSurfaceContainer = Color(0xFF1D2024)
val DarkSurfaceContainerHigh = Color(0xFF272A2F)
val DarkSurfaceContainerHighest = Color(0xFF32353A)

// Extended (non-scheme) status colors, tuned per theme in Theme.kt.
val SuccessLight = Color(0xFF2E7D32)
val SuccessDark = Color(0xFF8BD99C)
val WarningLight = Color(0xFF9A6A00)
val WarningDark = Color(0xFFF5C24C)
